title: Yuma Uchiumi
description: >
  Yuma Uchiumi's Blog site 
baseurl: ""
url: "http://yumaloop.github.io"

author:
  name: Yuma Uchiumi
  email: yumaloop@gmail.com
  github: yumaloop
  twitter: yumaloop
  facebook: yumauchiumi
  instagram: uchiumiyuma
  linkedin: yuma-uchiumi-699398151
  disqus_shortname: https-yumaloop-github-io

paginate: 5
paginate_path: page:num

sass:
  style: expanded

plugins:
  - jekyll-feed
  - jekyll-paginate

