title: Yuma Uchiumi
description: >
  Yuma Uchiumi's Homepage
baseurl: ""
url: "http://yumaloop.github.io"

author:
  name: Yuma Uchiumi
  email: yumaloop@gmail.com
  github: yumaloop
  twitter: yumaloop
  facebook: yumauchiumi
  instagram: uchiumiyuma
  linkedin: yuma-uchiumi-699398151
  disqus_shortname: https-yumaloop-github-io

text:
  sidebar_msg: Yuma Uchiumi's Blog like site containing some random things. Here are messy notes to organize my thoughts and sometimes useful information not on the Web. I hope you'll enjoy them.

collections:
  diary:
    output: true
    permalink: /diary/:name

paginate: 5
paginate_path: page:num

sass:
  style: expanded

plugins:
  - jekyll-feed
  - jekyll-paginate

